package entity.enumeration;

public enum AcademicLevel {

    KARDANI,
    CONTINUOUS_BACHELOR,
    DISCONTINUOUS_BACHELOR,
    CONTINUOUS_MASTER,
    DISCONTINUOUS_MASTER,
    DOCTORATE,
    CONTINUOUS_DOCTORATE,
    DISCONTINUOUS_SPECIALIZED_DOCTORATE

}