package entity.enumeration;

public enum UniversityType {

    GOVERNMENTAL_UNIVERSITY,
    NON_GOVERNMENTAL_UNIVERSITY,
    NON_PROFIT_UNIVERSITY,
    PARDIS_UNIVERSITY,
    EXCESS_CAPACITY_UNIVERSITY,
    PAYAM_NORE_UNIVERSITY,
    ELMIKARBORDI_UNIVERSITY,
    AZAD_UNIVERSITY

}