package repository.loanCategoryRepository;

import entity.loanCategory.HousingDepositLoanCategory;

public interface HousingDepositLoanCategoryRepository extends LoanCategoryRepository<HousingDepositLoanCategory>{
}
